const express = require("express");

const PDFDocument = require("pdfkit");

const router = express.Router();

router.post("/export-pdf", async (req, res) => {

  try {

    const data = req.body;

    const doc = new PDFDocument({
      margin: 50,
    });

    const filename = `seo-report-${Date.now()}.pdf`;

    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${filename}"`
    );

    res.setHeader(
      "Content-Type",
      "application/pdf"
    );

    doc.pipe(res);

    // =========================
    // TITLE
    // =========================

    doc
      .fontSize(28)
      .fillColor("#06b6d4")
      .text("SEO Scanner Pro Report", {
        align: "center",
      });

    doc.moveDown(2);

    // =========================
    // SEO SCORE
    // =========================

    doc
      .fontSize(20)
      .fillColor("black")
      .text(`SEO Score: ${data.seoScore}/100`);

    doc.moveDown();

    // =========================
    // META
    // =========================

    doc
      .fontSize(18)
      .fillColor("#111827")
      .text("Meta Information");

    doc.moveDown(0.5);

    doc
      .fontSize(12)
      .fillColor("black")
      .text(`Title: ${data.title || "Missing"}`);

    doc.text(
      `Description: ${data.metaDescription || "Missing"}`
    );

    doc.text(
      `Canonical: ${data.canonical || "Missing"}`
    );

    doc.moveDown(1.5);

    // =========================
    // TECH STACK
    // =========================

    doc
      .fontSize(18)
      .fillColor("#111827")
      .text("Tech Stack");

    doc.moveDown(0.5);

    doc
      .fontSize(12)
      .fillColor("black")
      .text(`jQuery: ${data.jqueryVersion}`);

    doc.text(`Bootstrap: ${data.bootstrapVersion}`);

    doc.moveDown(1.5);

    // =========================
    // PERFORMANCE
    // =========================

    doc
      .fontSize(18)
      .fillColor("#111827")
      .text("Performance");

    doc.moveDown(0.5);

    doc
      .fontSize(12)
      .fillColor("black")
      .text(`JS Files: ${data.performance.totalJSFiles}`);

    doc.text(
      `CSS Files: ${data.performance.totalCSSFiles}`
    );

    doc.text(
      `Total Images: ${data.performance.totalImages}`
    );

    doc.text(
      `Total Requests: ${data.performance.totalRequests}`
    );

    doc.text(
      `HTML Size: ${data.performance.htmlSize}`
    );

    doc.moveDown(1.5);

    // =========================
    // H1 TAGS
    // =========================

    doc
      .fontSize(18)
      .fillColor("#111827")
      .text("H1 Tags");

    doc.moveDown(0.5);

    if (data.h1Tags.length === 0) {

      doc.text("No H1 Tags Found");

    } else {

      data.h1Tags.forEach((tag) => {
        doc.text(`• ${tag}`);
      });
    }

    doc.moveDown(1.5);

    // =========================
    // BROKEN LINKS
    // =========================

    doc
      .fontSize(18)
      .fillColor("#111827")
      .text("Broken Links");

    doc.moveDown(0.5);

    if (data.brokenLinks.length === 0) {

      doc
        .fillColor("green")
        .text("No Broken Links Found");

    } else {

      data.brokenLinks.forEach((link) => {

        doc
          .fillColor("red")
          .text(`• ${link}`);
      });
    }

    doc.moveDown(1.5);

    // =========================
    // IMAGE ANALYSIS
    // =========================

    doc
      .fontSize(18)
      .fillColor("#111827")
      .text("Image Analysis");

    doc.moveDown(0.5);

    doc
      .fontSize(12)
      .fillColor("black")
      .text(`PNG: ${data.images.png}`);

    doc.text(`SVG: ${data.images.svg}`);

    doc.text(`WEBP: ${data.images.webp}`);

    doc.text(`JPG: ${data.images.jpg}`);

    doc.text(
      `Missing Alt Tags: ${data.missingAltCount}`
    );

    doc.moveDown(1.5);

    // =========================
    // ANALYTICS
    // =========================

    doc
      .fontSize(18)
      .fillColor("#111827")
      .text("Analytics");

    doc.moveDown(0.5);

    doc
      .fontSize(12)
      .fillColor("black")
      .text(
        `GTM: ${data.analytics.GTM.join(", ") || "Not Found"}`
      );

    doc.text(
      `GA4: ${data.analytics.GA4.join(", ") || "Not Found"}`
    );

    doc.moveDown(2);

    // FOOTER

    doc
      .fontSize(10)
      .fillColor("gray")
      .text(
        "Generated by SEO Scanner Pro",
        {
          align: "center",
        }
      );

    doc.end();

  } catch (error) {

    console.log(error);

    res.status(500).json({
      error: "PDF Export Failed",
    });
  }
});

module.exports = router;